### ISSUE TITLE
Jumps suddenly when the program is running

### ISSUE THREAD

**Issue by r2ten-catuncle** [McSib/e621_downloader#54] opened 2022-06-08 20:16 UTC
The downloads folder is not loaded when running the program for the first time
Causes it to crash when running later
how can i do
I've tried creating a "Downloads" folder, but it didn't work
(sorry for my grammar)

**Comment by McSib** [comment] 2022-06-26 06:00
Sorry for the late reply. The first question and thing I will need to diagnose the issue is for you to send the log file the program creates (it is a file with the extension “.log” and has the same name as the program). This file contains a large amount of debug information and general logging that will help me zero in and fix the bug you are encountering. Once you can send me that, I can determine what is happening. It may also be good too to provide your tag file, just if there is a bug or syntax error inside of that. When you can, reply with both of those, and I will reach back to you when I have the free time to do so. Have a great day, hope to hear from you soon.

**Comment by r2ten-catuncle** [comment] 2022-06-26 09:23
[e621_downloader.log](https://github.com/McSib/e621_downloader/files/8986314/e621_downloader.log)
`09:17:56 [TRACE] (1) e621_downloader::program: [src\program.rs:18] Starting downloader...
09:17:56 [INFO] The login file was created.
09:17:56 [INFO] If you wish to use your Blacklist, be sure to give your username and API hash key.
09:17:56 [INFO] Do not give out your API hash unless you trust this software completely, always treat your API hash like your own password.
09:18:07 [INFO] Read tag file...
09:18:07 [TRACE] (1) e621_downloader::program: [src\program.rs:35] Parsed tag data, now attempting to obtain user blacklist...
09:18:07 [TRACE] (1) e621_downloader::program: [src\program.rs:42] Unable to obtain blacklist...
09:18:07 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:93] Grabbing posts...
09:18:08 [INFO] [38;5;39m[3m"braeburned"[0m grabbed!
09:18:10 [INFO] [38;5;39m[3m"Taste_of_the_Order"[0m grabbed!
09:18:14 [INFO] [38;5;39m[3m"Good pictures"[0m grabbed!
`
Here, the program does not create a folder named "Download" when it is run for the first time, and the program crashes the second time it is run.

**Comment by McSib** [comment] 2022-06-27 03:30
Download the latest version if you have not yet, that version will have more in-depth information for me to inspect since the earlier version of the logger was lighter in that department, and then run that and send its log life to me. After that, open up CMD or Terminal in the directory with the exe and start it inside the console. When it crashes, send me a screenshot of what it's saying in the console. It can normally point me to whatever error is occurring at that moment and help me understand if it’s something happening on the server-side (which I can’t directly fix) or if it’s occurring on the client-side (which I can fix).

**Comment by r2ten-catuncle** [comment] 2022-06-27 04:26
[e621_downloader.log](https://github.com/McSib/e621_downloader/files/8988658/e621_downloader.log)
![don](https://user-images.githubusercontent.com/105350332/175859767-6ecf781d-039b-435e-9d2d-e1fb70cb9888.png)
I put the file in D:\, will that make a difference?

**Comment by McSib** [comment] 2022-06-27 04:33
Could you send me your tag file? I'm beginning to wonder if it is a syntax error related to that since the other requests are going through correctly.

**Comment by r2ten-catuncle** [comment] 2022-06-27 04:37
[tags.txt](https://github.com/McSib/e621_downloader/files/8988694/tags.txt)
This is the original file, I haven't edited it yet

**Comment by McSib** [comment] 2022-06-27 04:40
I managed to replicate the bug. What is happening is that the program crashes when grabbing the single post since you are in safe mode. The individual post there is explicit, so the post becomes null due to that. I will write up a fix and see if I can get you a working build soon. Sorry for that, it was an oversight on my part.

**Comment by McSib** [comment] 2022-06-27 08:21
This bug is now fixed. With this issue handled, I can now fully release 1.7.1 without any further delays. I hope you and others enjoy it when it releases. Have a wonderful day/night. :3

**Closed by McSib** 2022-06-27 08:21 UTC
Labels: bug, e621-client-bug, e621-client-request-sender-bug
