### ISSUE TITLE
Searching for multiple tags.

### ISSUE THREAD

**Issue by LordBarsdale** [McSib/e621_downloader#40] opened 2021-01-08 15:09 UTC
Ok. I have searched and searched, but I can't seem to find the answer anywhere. 

This downloader is apparently able to search for mutiple tags at once, but I am not sure if it means what I want. For example, lets say I want all 3d artwork of dragons. Not all images tagged 3d art. Not all images tagged dragon. Only images with both tagged. The benefit being I can get images that meet my criteria from multiple artists. Where would I post the tags? I've tried both tags together on the same line, and one below the other. The only category that would make sense is [general]. But that for sure doesn't work. I'm not even sure the program has this ability. 

This is probably a very simple answer that I am not seeing. This isn't really an issue, but I see nowhere else to post a general question. Thanks for taking time out of your day to read this.

**Comment by McSib** [comment] 2021-01-08 15:52
Hello, from what I'm gathering, you're looking to download all images with both tags `3d_(artwork)` and `dragon`. How you'd do this is putting these tags under `[general]` together as `3d_(artwork) dragon`. There's a catch though. The downloader has a limit to how many posts it can grab and download at the moment. If you go to the bottom of the readme.md, it talks about it in much greater detail. But to make it simple, there is a limit to how many posts you can get so e621 isn't flooded with requests and constant file grabs for hours becuase someone wanted all posts tagged `mammal`. It was one of the safe guards implemented to make sure that wouldn't become an issue, sad to say.

But, there is a bright side, I'm considering and am currently in the process of looking into adding a new section to my tag file which is for grabbing *all* posts to a tag, but with a clear disclaimer on how to use it. I could also implement a blacklist of sorts to ensure no one uses massive tags as a standalone search, such as someone downloading posts just tagged `mammal`. It's still only an idea right now, but I'm getting close to how I want to display it. There's also plenty of bug fixes needing to get done, so I'ma look into doing that as well.

**Comment by LordBarsdale** [comment] 2021-01-08 16:07
Thanks for your speedy reply. Combining the tags together on a single line below General was the first thing I tried though. I have no difficulty snatching single tags, but two or more doesn't work for some reason. I add the tags, start the .exe, and answer either yes or no. Then it hangs for a minute before displaying a memory allocation error before the window closely automatically. This happens whether I input yes or no. I'm not sure what causes this.

**Comment by McSib** [comment] 2021-01-08 16:35
If you could, could you send me the tag files entire contents?

**Comment by LordBarsdale** [comment] 2021-01-08 16:41
# This is the tag file that you will use so the program can know what tags to search.
# If you wish to comment in this file, simply put `#` at the beginning or end of line.

# Insert tags you wish to download in the appropriate group (remove all example tags and IDs with what you wish to download):

[artists]

[pools]

[sets]

[single-post]

[general]

3d_(artwork) dragon

**Comment by McSib** [comment] 2021-01-08 17:51
Okay, I'll run some tests soon and see what's causing the issue, should be a simple fix (though I've never heard of a memory allocation error happening with my program before).

**Comment by LordBarsdale** [comment] 2021-01-08 18:01
Appreciated!

**Comment by McSib** [comment] 2021-01-08 20:47
I will be releasing a hotfix here within the next 30 minutes, so feel free to try it now as it should be fixed. From what I saw, there were new tag categories added to e621, and because of this, my program didn't know how to handle it other than screaming it reached unreachable code. I have fixed this now that the issue is figured out. Was able to download images with your tag set perfectly fine 👍

**Closed by McSib** 2021-01-08 20:47 UTC
Labels: bug, e621-client-request-sender-bug, question

**Comment by LordBarsdale** [comment] 2021-01-08 23:05
Wow man. You're amazing. Thank you for your program.

**Comment by McSib** [comment] 2021-01-09 01:47
No problem, enjoy my software and have a great day! :)
